export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const SET_BLOCKS_FROM_NODE = 'SET_BLOCKS_FROM_NODE';
export const SET_BLOCKS_FROM_NODE_FAILURE = 'SET_BLOCKS_FROM_NODE_FAILURE';